name: spanticom
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_osm_plugin: ^0.53.2
  percent_indicator: ^4.2.3
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  logging: ^1.0.1
  sqflite: ^2.2.6
  sqflite_common_ffi_web: ^0.3.4
  path_provider: ^2.0.14
  equatable: ^2.0.5
  get: ^4.1.4
  get_it: ^7.2.0
  font_awesome_flutter: ^9.0.0
  flutter_spinkit: ^5.0.0
  flutter_form_builder: ^9.0.0
  form_builder_validators: ^9.0.0
  image_picker: ^0.8.0+3
  permission_handler: ^10.2.0
  shimmer: ^2.0.0
  path: ^1.8.2
  flutter_randomcolor: ^1.0.14
  flutter_rounded_date_picker: ^3.0.3
  flutter_date_pickers: ^0.3.1
  swipebuttonflutter: ^1.0.0
  syncfusion_flutter_charts: ^21.1.38
  carousel_slider: ^4.2.1
  photo_view: ^0.14.0
  firebase_core: ^2.4.1 # add dependency for Firebase Core 
  firebase_auth: ^4.2.5
  firebase_crashlytics: ^3.0.11
  firebase_messaging: ^14.2.1 
  firebase_storage: ^11.0.10
  cloud_firestore: ^4.8.0 
  url_launcher: ^6.1.14

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.9.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21 

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/edukasiBullying/
    - assets/icon/
  fonts:
    - family: Anydore
      fonts:
        - asset: assets/fonts/Anydore.otf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Italic.ttf
          style: italic
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
          weight: 600

  